import { exactKey } from './duplicate-detector.js';
async function identityId(order){const key=exactKey(order);if(!key)return null;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key));return `identity_${[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}`;}
export class OrderStore {
 constructor(user){this.uid=user.uid;this.root=firebase.firestore().collection('users').doc(user.uid);}
 collection(name){return this.root.collection(name);} orders(){return this.collection('orders');} profiles(){return this.collection('importProfiles');} batches(){return this.collection('importBatches');}
 async listOrders(){const snapshot=await this.orders().get();return snapshot.docs.map(doc=>({...doc.data(),internalId:doc.id}));}
 async listProfiles(){const snapshot=await this.profiles().get();return snapshot.docs.map(doc=>({...doc.data(),id:doc.id}));}
 async saveProfile(profile){await this.profiles().doc(profile.id).set({...profile,createdBy:this.uid},{merge:true});}
 async deleteProfile(id){await this.profiles().doc(id).delete();}
 async saveOrder(order){const now=new Date().toISOString(),id=order.createdAt?order.internalId:(await identityId(order))||order.internalId;const ref=this.orders().doc(id),data={...order,internalId:id,createdAt:order.createdAt||now,updatedAt:now};if(id!==order.internalId)await firebase.firestore().runTransaction(async tx=>{if((await tx.get(ref)).exists)throw Error('This Order ID already exists for this source.');tx.set(ref,data);});else await ref.set(data);return id;}
 async deleteOrders(ids){let count=0;for(const id of ids){await this.orders().doc(id).delete();count++;}return count;}
 async saveImport(rows,metadata){const batchId=crypto.randomUUID(),now=new Date().toISOString();await this.batches().doc(batchId).set({batchId,importedAt:now,importedBy:this.uid,savedCount:0,state:'SAVING',...metadata});let saved=0;try{for(const row of rows){if(row.duplicateKind==='EXACT')continue;const order={...row,importBatchId:batchId,createdAt:now,updatedAt:now};delete order.rowNumber;delete order.duplicateKind;const id=(await identityId(order))||order.internalId,ref=this.orders().doc(id);if(id!==order.internalId){const created=await firebase.firestore().runTransaction(async tx=>{if((await tx.get(ref)).exists)return false;tx.set(ref,{...order,internalId:id});return true;});if(!created)continue;}else await ref.set(order);saved++;}await this.batches().doc(batchId).update({savedCount:saved,state:'COMPLETE'});return {batchId,saved};}catch(error){await this.batches().doc(batchId).update({savedCount:saved,state:'PARTIAL',errorMessage:String(error.message)}).catch(()=>{});throw Error(`${saved} of ${rows.length} orders saved. Batch ${batchId.slice(0,8)} is partial. ${error.message}`);}}
}
