import { FIELDS } from './order-schema.js';
import { suggestMapping,validateMapping } from './import-mapper.js';
import { normalizeOrder } from './order-normalizer.js';
import { validateOrder } from './import-validator.js';
import { classifyDuplicate } from './duplicate-detector.js';
import { makeProfile,matchProfile,applyProfile } from './import-profiles.js';
import { readFile,parsePaste } from './spreadsheet-reader.js';
import { prepareImport,countStatuses } from './import-engine.js';
import { OrderStore } from './order-store.js';
import { loadMasterData,loadContactRequired } from './master-data.js';
import { buildMasterIndex,customerCandidates,stopCandidates,contactCandidates } from './customer-matcher.js';
import { resolveOrder } from './order-readiness.js';
import { saveDraft,loadDraft,deleteDraft,beginReturn,takeAssignment } from './import-return-context.js';
const $=id=>document.getElementById(id),PAGE=50,PREVIEW_PAGE=30;
const state={uid:null,store:null,accountProfile:null,authGeneration:0,orders:[],profiles:[],master:null,index:null,contactRequired:false,table:null,mapping:[],preview:[],included:new Set(),selected:new Set(),page:0,previewPage:0,method:'',filename:'',profile:null,editing:null,busy:false,sessionId:null};
const element=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text??'');if(cls)node.className=cls;return node;};
const cell=(tr,text,cls)=>{const td=element('td',text,cls);tr.append(td);return td;};
function message(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);$('notice').hidden=!text;}
function fail(error){message(error?.message||'Something went wrong. Please try again.',true);}
function showRetry(text,action){message(text,true);const button=element('button','Retry','quiet');button.type='button';button.addEventListener('click',action);$('notice').append(' ',button);}
function setBusy(value){state.busy=value;document.querySelectorAll('button').forEach(button=>button.disabled=value);if(!value){renderOrders();if(state.preview.length)renderPreview();}}
function filtered(){const q=$('search').value.trim().toLowerCase(),status=$('status-filter').value,date=$('date-filter').value,sort=$('sort').value;const rows=state.orders.filter(order=>(!status||order.status===status)&&(!date||order.deliveryDate===date)&&(!q||[order.orderId,order.customerName,order.address,order.phone].some(value=>String(value||'').toLowerCase().includes(q))));rows.sort((a,b)=>sort==='oldest'?String(a.createdAt).localeCompare(String(b.createdAt)):sort==='date'?String(a.deliveryDate||'9999').localeCompare(String(b.deliveryDate||'9999')):sort==='customer'?String(a.customerName||'').localeCompare(String(b.customerName||'')):String(b.createdAt).localeCompare(String(a.createdAt)));return rows;}
function renderMetrics(){const counts=countStatuses(state.orders);$('count-total').textContent=state.orders.length.toLocaleString();$('count-ready').textContent=counts.READY.toLocaleString();$('count-review').textContent=counts.NEEDS_REVIEW.toLocaleString();$('count-duplicate').textContent=counts.DUPLICATE.toLocaleString();}
function renderOrders(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/PAGE));state.page=Math.min(state.page,pages-1);const pageRows=rows.slice(state.page*PAGE,(state.page+1)*PAGE),body=$('orders-body');body.replaceChildren();for(const order of pageRows){const tr=element('tr'),select=cell(tr,'');const box=element('input');box.type='checkbox';box.checked=state.selected.has(order.internalId);box.dataset.selectId=order.internalId;box.setAttribute('aria-label',`Select ${order.orderId}`);select.append(box);cell(tr,order.orderId,'strong');cell(tr,order.customerName||'—');cell(tr,order.deliveryAddress||order.address||'Address needed');cell(tr,order.deliveryDate||'—');const outcomeCell=cell(tr,'');outcomeCell.append(element('span',order.status.replace('_',' '),`badge ${order.status.toLowerCase()}`));if(['DELIVERED','FAILED'].includes(order.executionStatus))outcomeCell.append(element('small',`Delivery: ${order.executionStatus.toLowerCase()}`,'issue'));const edit=element('button','Edit','quiet');edit.type='button';edit.dataset.editId=order.internalId;cell(tr,'').append(edit);body.append(tr);}$('empty-state').hidden=rows.length>0;$('page-info').textContent=rows.length?`${state.page*PAGE+1}–${Math.min(rows.length,(state.page+1)*PAGE)} of ${rows.length}`:'0 orders';$('prev-page').disabled=state.busy||state.page===0;$('next-page').disabled=state.busy||state.page>=pages-1;$('selection-count').textContent=`${state.selected.size} selected`;$('delete-selected').disabled=state.busy||!state.selected.size;$('plan-selected').disabled=state.busy||!state.selected.size;$('plan-selected').textContent=state.selected.size?'Plan '+state.selected.size+' selected order'+(state.selected.size===1?'':'s'):'Plan selected orders';$('select-page').checked=!!pageRows.length&&pageRows.every(order=>state.selected.has(order.internalId));}
function renderProfiles(){const select=$('profile-select');select.replaceChildren(new Option('Suggested mapping',''));state.profiles.forEach(profile=>select.add(new Option(profile.name,profile.id)));if(state.profile)select.value=state.profile.id;$('delete-profile').hidden=!state.profile;}
function renderMapping(){const grid=$('mapping-grid');grid.replaceChildren();state.table.headers.forEach((header,index)=>{const label=element('label');label.append(element('span',header));const select=element('select');select.dataset.mappingIndex=index;select.add(new Option('Ignore column',''));FIELDS.forEach(([key,title])=>select.add(new Option(title,key)));select.value=state.mapping[index]||'';label.append(select);grid.append(label);});}
function startTable(table,method,filename=''){state.table=table;state.method=method;state.filename=filename;state.preview=[];state.previewPage=0;state.sessionId=crypto.randomUUID();state.profile=matchProfile(state.profiles,table.headers);state.mapping=state.profile?applyProfile(state.profile,table.headers):suggestMapping(table.headers).map(item=>item.field);renderProfiles();renderMapping();$('source-summary').textContent=`${filename?`${filename} · `:''}${table.rows.length} rows · ${table.headers.length} columns${state.profile?` · ${state.profile.name} recognized`:''}`;$('mapping-stage').hidden=false;$('preview-stage').hidden=true;$('import-panel').hidden=false;message('Review the detected columns, then preview the orders.');}
function reclassifyPreview(initial=false){const prior=new Map(state.preview.map(order=>[order.internalId,order.status])),seen=[...state.orders];state.preview=state.preview.map(row=>{const seed={...row,duplicateKind:null,validationIssues:[...(row.baseValidationIssues||[])]};let order=resolveOrder(seed,state.index,{contactRequired:state.contactRequired}).order;const duplicate=classifyDuplicate(order,seen);if(duplicate){order={...order,duplicateKind:duplicate.kind,status:'DUPLICATE',validationIssues:[...order.validationIssues,duplicate.message]};}seen.push(order);return order;});for(const row of state.preview){if(initial){if(row.status==='READY')state.included.add(row.internalId);}else if(row.status==='READY'&&prior.get(row.internalId)!=='READY')state.included.add(row.internalId);if(row.duplicateKind==='EXACT')state.included.delete(row.internalId);}renderPreview();queueDraft();}
function selectControl(type,row,items,selected,labelFn){const select=element('select');select.dataset.resolution=type;select.dataset.rowId=row.internalId;select.setAttribute('aria-label',`Select ${type} for ${row.orderId}`);select.add(new Option(`Select ${type}`,'',!selected,!selected));items.forEach(item=>select.add(new Option(labelFn(item),item.id)));select.value=selected||'';return select;}
function maintenanceButton(kind,row,text){const button=element('button',text,'quiet');button.type='button';button.dataset.maintenance=kind;button.dataset.rowId=row.internalId;return button;}
function renderPreview(){const counts=countStatuses(state.preview);$('preview-counts').textContent=`${state.preview.length} rows · ${counts.READY} ready · ${counts.NEEDS_REVIEW} need review · ${counts.DUPLICATE} duplicate${state.contactRequired?' · Contact Required ON':' · Contact Required OFF'}`;const pages=Math.max(1,Math.ceil(state.preview.length/PREVIEW_PAGE));state.previewPage=Math.min(state.previewPage,pages-1);const body=$('preview-body');body.replaceChildren();for(const order of state.preview.slice(state.previewPage*PREVIEW_PAGE,(state.previewPage+1)*PREVIEW_PAGE)){const tr=element('tr');cell(tr,order.rowNumber);cell(tr,order.orderId);const customers=customerCandidates(order,state.index),customer=order.customerId?state.index.customerById.get(order.customerId):null,stops=customer?stopCandidates(customer.id,state.index):[],contacts=customer?contactCandidates(customer.id,order.savedStopId,state.index):[];
 const customerCell=cell(tr,'','preview-customer');customerCell.append(element('strong',order.customerName||'Customer needed'));if(customers.length>1)customerCell.append(selectControl('customer',order,customers,order.customerId,item=>item.name));
 const stopCell=cell(tr,'','preview-stop'),stop=stops.find(item=>item.id===order.savedStopId);const stopBox=element('div',undefined,'resolution');stopBox.append(stops.length>1?selectControl('stop',order,stops,order.savedStopId,item=>`${item.label||item.name} — ${item.address}`):element('span',stop?`${stop.label||stop.name} — ${stop.address}`:'No delivery stop selected'));stopBox.append(maintenanceButton(order.customerId?'stop':'stop',order,order.customerId?'＋ Add New Delivery Stop':'＋ Add Stop'));if(!stop&&state.contactRequired)stopBox.append(maintenanceButton('both',order,'＋ Add Stop + Contact'));stopCell.append(stopBox);
 const contactCell=cell(tr,'','preview-contact'),contact=contacts.find(item=>item.id===order.contactId),contactBox=element('div',undefined,'resolution');contactBox.append(contacts.length>1?selectControl('contact',order,contacts,order.contactId,item=>`${item.name}${item.role?` — ${item.role}`:''}${item.phone?` — ${item.phone}`:''}`):element('span',contact?`${contact.name}${contact.phone?` · ${contact.phone}`:''}`:'No contact selected'));if(customer)contactBox.append(maintenanceButton('contact',order,'＋ Add Contact'));contactCell.append(contactBox);
 const issue=cell(tr,'');issue.append(element('span',order.status.replace('_',' '),`badge ${order.status.toLowerCase()}`));if(order.resolutionCode)issue.append(element('small',order.resolutionCode.replaceAll('_',' '),'issue'));if(order.validationIssues.length)issue.append(element('small',order.validationIssues.join(' '),'issue'));const box=element('input');box.type='checkbox';box.dataset.previewId=order.internalId;box.checked=state.included.has(order.internalId);box.disabled=order.duplicateKind==='EXACT';box.setAttribute('aria-label',`Include row ${order.rowNumber}`);cell(tr,'').append(box);body.append(tr);}
 $('preview-range').textContent=`Showing ${Math.min(state.preview.length,state.previewPage*PREVIEW_PAGE+1)}–${Math.min(state.preview.length,(state.previewPage+1)*PREVIEW_PAGE)} of ${state.preview.length}`;$('preview-prev').disabled=state.previewPage===0;$('preview-next').disabled=state.previewPage>=pages-1;$('confirm-import').textContent=`Import ${state.included.size} selected order${state.included.size===1?'':'s'}`;$('confirm-import').disabled=state.busy||!state.included.size;}
let draftTimer=null;function queueDraft(){clearTimeout(draftTimer);if(!state.preview.length)return;draftTimer=setTimeout(()=>persistDraft().catch(()=>{}),250);}
async function persistDraft(){if(!state.uid||!state.sessionId||!state.preview.length)return;await saveDraft(state.uid,{sessionId:state.sessionId,table:state.table,mapping:state.mapping,preview:state.preview,included:[...state.included],previewPage:state.previewPage,method:state.method,filename:state.filename,profileId:state.profile?.id||null});sessionStorage.setItem(`goroutex-order-hub-active:${state.uid}`,state.sessionId);}
async function beginMaintenance(rowId,kind){const row=state.preview.find(item=>item.internalId===rowId);if(!row)return;try{await persistDraft();beginReturn({uid:state.uid,sessionId:state.sessionId,rowId,kind,customerId:row.customerId||null,customerName:row.customerName||'',shipToCode:row.shipToCode||'',address:row.rawAddress||row.address||'',contactName:row.rawInput?.contactName||'',phone:row.rawInput?.phone||row.phone||'',savedStopId:row.savedStopId||null});location.href='app.html#page-add-stop';}catch(error){fail(error);}}
async function restoreDraft(assignment){const id=assignment?.sessionId||sessionStorage.getItem(`goroutex-order-hub-active:${state.uid}`);if(!id)return false;const draft=await loadDraft(state.uid,id);if(!draft?.preview?.length)return false;state.sessionId=id;state.table=draft.table;state.mapping=draft.mapping;state.preview=draft.preview;state.included=new Set(draft.included||[]);state.previewPage=draft.previewPage||0;state.method=draft.method;state.filename=draft.filename;state.profile=state.profiles.find(profile=>profile.id===draft.profileId)||null;renderProfiles();renderMapping();$('source-summary').textContent=`${state.filename?`${state.filename} · `:''}${state.table.rows.length} rows · ${state.table.headers.length} columns · restored import`;$('import-panel').hidden=false;$('mapping-stage').hidden=false;$('preview-stage').hidden=false;if(assignment){const row=state.preview.find(item=>item.internalId===assignment.rowId);if(row){if(assignment.customerId)row.customerId=assignment.customerId;if(assignment.savedStopId){row.savedStopId=assignment.savedStopId;row.contactId=null;}if(assignment.contactId)row.contactId=assignment.contactId;const index=state.preview.indexOf(row);state.previewPage=Math.floor(index/PREVIEW_PAGE);}else message('Import restored, but the original order row was not found.',true);}reclassifyPreview();return true;}
async function refresh(){
  const uid=state.uid,store=state.store;
  const [orders,profiles]=await Promise.allSettled([store.listOrders(),store.listProfiles()]);
  if(state.uid!==uid||state.store!==store)return;
  if(orders.status==='fulfilled'){state.orders=orders.value;state.selected.clear();renderMetrics();renderOrders();}
  else showRetry('Orders unavailable: '+orders.reason.message,()=>{void refresh();});
  if(profiles.status==='fulfilled'){state.profiles=profiles.value;renderProfiles();}
  else showRetry('Import profiles unavailable: '+profiles.reason.message,()=>{void refresh();});
  return { ordersReady: orders.status==='fulfilled', profilesReady: profiles.status==='fulfilled' };
}
async function refreshMaster(){const uid=state.uid;const master=await loadMasterData(uid,{forceReload:true});if(state.uid!==uid)return;const contactRequired=await loadContactRequired(uid);if(state.uid!==uid)return;state.master=master;state.index=buildMasterIndex(master);state.contactRequired=contactRequired;}
async function saveManual(addAnother=false){if(state.busy)return;const previous=state.editing?state.orders.find(item=>item.internalId===state.editing):null;const retained=previous?.rawInput||Object.fromEntries(FIELDS.filter(([key])=>previous&&Object.hasOwn(previous,key)).map(([key])=>[key,previous[key]]));const raw={...retained,...Object.fromEntries(new FormData($('manual-form')).entries())};if(previous){if(!raw.address)raw.address=previous.deliveryAddress||previous.address||'';if(!raw.contactName)raw.contactName=previous.contactName||'';for(const key of ['latitude','longitude'])if(raw[key]==null&&previous[key]!=null)raw[key]=previous[key];}const {order,issues}=normalizeOrder(raw,{source:previous?.source||'MANUAL',internalId:state.editing||undefined});Object.assign(order,validateOrder(order,issues));const duplicate=classifyDuplicate(order,state.orders.filter(item=>item.internalId!==state.editing));if(duplicate){order.status='DUPLICATE';order.validationIssues.push(duplicate.message);}if(previous){order.createdAt=previous.createdAt;order.importBatchId=previous.importBatchId;for(const key of ['customerId','savedStopId','contactId','contactPhone'])order[key]=previous[key]||null;order.deliveryAddress=order.address||previous.deliveryAddress||null;order.locationStatus=previous.locationStatus||order.locationStatus;for(const key of ['executionStatus','driverRouteId','executionUpdatedAt'])if(previous[key]!=null)order[key]=previous[key];}if(duplicate?.kind==='EXACT'&&!state.editing){message('This Order ID already exists. Edit the existing order instead.',true);return;}setBusy(true);try{await state.store.saveOrder(order);await refresh();message(`${order.orderId} saved as ${order.status.replace('_',' ')}.`);if(addAnother){$('manual-form').reset();state.editing=null;$('manual-title').textContent='Add order';}else{$('manual-panel').hidden=true;state.editing=null;}}catch(error){fail(error);}finally{setBusy(false);}}
function openEdit(id){const order=state.orders.find(item=>item.internalId===id);if(!order)return;state.editing=id;$('manual-title').textContent='Edit order';$('manual-form').reset();for(const field of $('manual-form').elements)if(field.name&&(order.rawInput?.[field.name]??order[field.name])!=null)field.value=field.name==='address'?(order.deliveryAddress||order.address||''):(order.rawInput?.[field.name]??order[field.name]);$('manual-panel').hidden=false;$('manual-panel').scrollIntoView({behavior:'smooth'});}
function setup(){ $('open-import').onclick=()=>{$('import-panel').hidden=false;$('import-panel').scrollIntoView({behavior:'smooth'});};$('close-import').onclick=()=>{$('import-panel').hidden=true;};$('open-manual').onclick=()=>{state.editing=null;$('manual-title').textContent='Add order';$('manual-form').reset();$('manual-panel').hidden=false;$('manual-panel').scrollIntoView({behavior:'smooth'});};$('close-manual').onclick=()=>{$('manual-panel').hidden=true;state.editing=null;};$('manual-form').onsubmit=event=>{event.preventDefault();saveManual();};$('save-add').onclick=()=>saveManual(true);
 $('file-input').onchange=async event=>{const file=event.target.files[0];if(!file)return;$('mapping-stage').hidden=true;$('preview-stage').hidden=true;message(`Reading ${file.name}…`);try{startTable(await readFile(file),'FILE',file.name);}catch(error){fail(error);}};$('parse-paste').onclick=()=>{try{startTable(parsePaste($('paste-input').value),'PASTE');}catch(error){fail(error);}};
 $('profile-select').onchange=event=>{state.profile=state.profiles.find(profile=>profile.id===event.target.value)||null;state.mapping=state.profile?applyProfile(state.profile,state.table.headers):suggestMapping(state.table.headers).map(item=>item.field);renderMapping();renderProfiles();};$('delete-profile').onclick=async()=>{if(!state.profile||!confirm(`Delete profile ${state.profile.name}?`))return;try{await state.store.deleteProfile(state.profile.id);state.profiles=await state.store.listProfiles();state.profile=null;state.mapping=suggestMapping(state.table.headers).map(item=>item.field);renderMapping();renderProfiles();message('Import Profile deleted.');}catch(error){fail(error);}};$('mapping-grid').onchange=event=>{if(event.target.matches('select[data-mapping-index]'))state.mapping[Number(event.target.dataset.mappingIndex)]=event.target.value;};
 $('preview-import').onclick=()=>{try{if(!state.index)throw Error('Saved stops are unavailable. Retry loading data before previewing an import.');validateMapping(state.mapping);state.preview=prepareImport(state.table,state.mapping,state.orders,{source:state.method}).map(row=>({...row,baseValidationIssues:row.validationIssues.filter(issue=>!issue.includes('already exists')&&!issue.includes('match another order'))}));state.included=new Set();reclassifyPreview(true);$('preview-stage').hidden=false;$('preview-stage').scrollIntoView({behavior:'smooth'});message('Preview is ready. Resolve any missing customer, stop or required contact.');}catch(error){fail(error);}};$('back-mapping').onclick=()=>{$('preview-stage').hidden=true;};
 $('preview-body').onchange=event=>{const target=event.target,row=state.preview.find(item=>item.internalId===target.dataset.rowId);if(target.dataset.previewId){target.checked?state.included.add(target.dataset.previewId):state.included.delete(target.dataset.previewId);renderPreview();queueDraft();return;}if(!row)return;if(target.dataset.resolution==='customer'){row.customerId=target.value||null;row.savedStopId=null;row.contactId=null;}if(target.dataset.resolution==='stop'){row.savedStopId=target.value||null;row.contactId=null;}if(target.dataset.resolution==='contact')row.contactId=target.value||null;reclassifyPreview();};$('preview-body').onclick=event=>{const button=event.target.closest('[data-maintenance]');if(button)beginMaintenance(button.dataset.rowId,button.dataset.maintenance);};$('preview-prev').onclick=()=>{state.previewPage--;renderPreview();queueDraft();};$('preview-next').onclick=()=>{state.previewPage++;renderPreview();queueDraft();};
 $('confirm-import').onclick=async()=>{if(state.busy||!state.included.size)return;const saveProfile=$('save-profile').checked,name=$('profile-name').value.trim();if(saveProfile&&!name&&!state.profile){message('Enter a profile name.',true);return;}setBusy(true);try{await refreshMaster();reclassifyPreview();const rows=state.preview.filter(row=>state.included.has(row.internalId)),counts=countStatuses(state.preview);if(!rows.length)throw Error('No rows remain selected after revalidation.');const result=await state.store.saveImport(rows,{importMethod:state.method,sourceFilename:state.filename||null,profileId:state.profile?.id||null,totalRows:state.preview.length,readyCount:counts.READY,reviewCount:counts.NEEDS_REVIEW,duplicateCount:counts.DUPLICATE});let profileError=null;if(saveProfile)try{await state.store.saveProfile(makeProfile(name||state.profile.name,state.table.headers,state.mapping,state.profile?.id));}catch(error){profileError=error;}await refresh();$('import-panel').hidden=true;$('file-input').value='';sessionStorage.removeItem(`goroutex-order-hub-active:${state.uid}`);await deleteDraft(state.uid,state.sessionId).catch(()=>{});message(`${result.saved} orders saved in batch ${result.batchId.slice(0,8)}.${profileError?' Orders saved, but the profile could not be saved.':''}`,!!profileError);}catch(error){fail(error);await refresh().catch(()=>{});}finally{setBusy(false);}};
 for(const id of ['search','status-filter','date-filter','sort'])$(id).addEventListener(id==='search'?'input':'change',()=>{state.page=0;renderOrders();});$('prev-page').onclick=()=>{state.page--;renderOrders();};$('next-page').onclick=()=>{state.page++;renderOrders();};$('orders-body').onclick=event=>{if(event.target.dataset.editId)openEdit(event.target.dataset.editId);};$('orders-body').onchange=event=>{const id=event.target.dataset.selectId;if(id){event.target.checked?state.selected.add(id):state.selected.delete(id);renderOrders();}};$('select-page').onchange=event=>{filtered().slice(state.page*PAGE,(state.page+1)*PAGE).forEach(order=>event.target.checked?state.selected.add(order.internalId):state.selected.delete(order.internalId));renderOrders();};$('plan-selected').onclick=async()=>{if(state.busy||!state.selected.size)return;if(!window.GoRouteXAccountContext?.get()){message('Plan unavailable. Retry loading your account before sending orders to Planning.',true);return;}setBusy(true);try{await refreshMaster();const orders=state.orders.filter(order=>state.selected.has(order.internalId));const toolkit=window.RoutePlannerProduct;const plan=toolkit?.getPlanDefinition?.(toolkit.getCurrentPlan(state.accountProfile||{}));const selection=window.GoRouteXOrderPlan.prepare(orders,state.master.stops,plan?.limits?.maxSelectableStops);const updatedAt=new Date().toISOString();const saved=await window.RoutePlannerStorage.saveSelection({selectedCustomers:selection.stopIds,selectedAddresses:selection.selectedAddresses,updatedAt},{profile:state.accountProfile||{}});if(!saved?.success)throw Error(saved?.error||'Could not send the selected stops to route planning.');window.GoRouteXOrderPlan.save(state.uid,selection);location.href='app.html?page=page-select-stops#page-select-stops';}catch(error){fail(error);$('notice').scrollIntoView({behavior:'smooth',block:'center'});setBusy(false);}};$('delete-selected').onclick=async()=>{if(!state.selected.size||!confirm(`Delete ${state.selected.size} selected orders?`))return;setBusy(true);try{const count=await state.store.deleteOrders([...state.selected]);await refresh();message(`${count} orders deleted.`);}catch(error){fail(error);await refresh().catch(()=>{});}finally{setBusy(false);}};}
setup();
if(!window.FirebaseApp?.auth?.onAuthStateChange) message('Firebase is unavailable. Reload and check your connection.',true);
else window.FirebaseApp.auth.onAuthStateChange(async user=>{
  const generation=++state.authGeneration;
  window.GoRouteXAccountContext?.clear();
  state.uid=null;state.store=null;state.accountProfile=null;
  $('workspace').hidden=true;
  if(!user){location.href='login.html?next='+encodeURIComponent('order-hub.html');return;}
  if(window.FirebaseApp.auth.isDriverAccount?.(user)){location.replace('driver.html');return;}
  window.GoRouteXSidebar?.setAccount({name:'Loading account…',plan:'Loading plan…'});
  let identity;
  try {
    identity=await window.GoRouteXAccountContext.loadIdentity(user);
    if(generation!==state.authGeneration||window.FirebaseApp.auth.getCurrentUser()?.uid!==identity.uid)return;
  } catch(error) {
    if(generation!==state.authGeneration)return;
    window.GoRouteXSidebar?.setAccount({name:'Account unavailable',plan:'Plan unavailable'});
    showRetry('Unable to load your account: '+error.message,()=>location.reload());
    return;
  }
  state.uid=user.uid;
  state.accountProfile=identity.profile;
  state.store=new OrderStore(user);
  let planLabel='Plan unavailable';
  try {planLabel=window.GoRouteXAccountContext.resolvePlan(identity).planLabel;}
  catch(error){console.warn('ORDER_HUB_PLAN_UNAVAILABLE',{code:String(error?.code||'unknown').slice(0,60)});}
  window.GoRouteXSidebar?.setAccount({name:identity.displayName,plan:planLabel});
  $('workspace').hidden=false;
  const [orders,master]=await Promise.allSettled([refresh(),refreshMaster()]);
  if(generation!==state.authGeneration)return;
  if(orders.status==='rejected')showRetry('Orders unavailable: '+orders.reason.message,()=>{void refresh();});
  if(master.status==='rejected')showRetry('Saved stops unavailable: '+master.reason.message,()=>{void refreshMaster().catch(error=>showRetry('Saved stops unavailable: '+error.message,()=>location.reload()));});
  if(master.status==='fulfilled' && orders.status==='fulfilled' && orders.value.ordersReady && orders.value.profilesReady) {
    try {
      const assignment=takeAssignment(user.uid);
      const restored=await restoreDraft(assignment);
      if(restored)message(assignment?'Returned to the original import row.':'Import session restored.');
    } catch(error) {showRetry('Import draft unavailable: '+error.message,()=>location.reload());}
  }
});
