import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const sources=['planning/planning-state.js','planning/manual-assignment-page.js','planning/manual-assignment-dnd.js'].map(read);
function fixture(){
 const cost={preview:0,writes:0,netlify:0,eta:0};
 const c=vm.createContext({console,MAX_WAYPOINTS_PER_ROUTE:8,DEFAULT_ROUTE_START_TIME:'09:00',getDefaultStayMinutes:()=>15,getDefaultStayMinutesForStop:()=>15,normalizeStayMinutes:n=>Number(n)||15,getPreferredPlanningTime:()=> '09:00',getDateKey:()=> '2026-10-03',isManualRouteListType:s=>/^route\d+$/.test(s),getRouteKeyIndex:s=>Number(s.slice(5))-1,getManualRouteGroupLabel:s=>s,getRouteColor:()=> '#123',assignRouteColors:x=>x,hydrateManualDetours(){},rememberRouteManualDetours(){},restoreRouteManualDetours(){},getRouteCacheKeyFromStops:s=>s.map(x=>typeof x==='string'?x:x.id).join(','),getFilledRouteStopConfigs:()=>[],getRouteStopStayMinutes:()=>15,getStopDisplayDataById:id=>({uniqueId:id,Name:id,Address:id}),messageBarPg2:{textContent:''},document:{querySelectorAll:()=>[]},setTimeout:f=>f(),draggedItemElement:null,draggedItemOriginalListType:null,appLog(){}});
 c.window=c;sources.forEach(s=>vm.runInContext(s,c));
 vm.runInContext("initializePlanningDraftState(); selectedCustomers=new Set(['a','b','c']);",c);
 c.populateManualAssignmentLists=()=>{};c.addSimpleMarkersForMasterList=()=>{};c.updateRouteLines=()=>cost.preview++;c.updateConfirmRouteButtonState=()=>{};
 return {c,cost,run:s=>vm.runInContext(s,c),json:s=>JSON.parse(vm.runInContext('JSON.stringify('+s+')',c))};
}
function element(dataset={}){const events=new Map(),classes=new Set(['filled']);return {dataset,classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},events,addEventListener(t,f){const s=events.get(t)||new Set();s.add(f);events.set(t,s)},removeEventListener(t,f){events.get(t)?.delete(f)}}}
function drag(c,from,to){const data=new Map();const dataTransfer={setData:(k,v)=>data.set(k,v),getData:k=>data.get(k)||''};c.handleSlotDragStart({currentTarget:from,dataTransfer});c.handleSlotDrop({currentTarget:to,dataTransfer,preventDefault(){}})}
test('Manual Assignment modules declare functions without touching DOM or services',()=>{const c=vm.createContext({});sources.forEach(s=>vm.runInContext(s,c));assert.equal(typeof c.handleGoToManualAssignPage,'function');assert.equal(typeof c.handleSlotDrop,'function');assert.equal(c.draggedItemElement,undefined)});
test('slot drag to empty target moves the complete entry and preserves live aliases',()=>{const {c,run,json,cost}=fixture();run("setRouteSlotEntry('route1',0,{location:'a',stay:25})");drag(c,element({listType:'route1',slot:'0',customerId:'a'}),element({listType:'route2',slot:'1'}));assert.equal(json("getRouteSlotEntry('route1',0)").location,null);assert.deepEqual(json("getRouteSlotEntry('route2',1)"),{location:'a',stay:25});assert.deepEqual(json('manualRoute2Waypoints'),['a']);assert.deepEqual(json('window._activeRoutes[0].stops.map(s=>s.id)'),['a']);assert.deepEqual(cost,{preview:1,writes:0,netlify:0,eta:0})});
test('drop onto occupied slot swaps entries rather than losing either stop',()=>{const {c,run,json}=fixture();run("setRouteSlotEntry('route1',0,{location:'a',stay:25});setRouteSlotEntry('route2',0,{location:'b',stay:30})");drag(c,element({listType:'route1',slot:'0',customerId:'a'}),element({listType:'route2',slot:'0'}));assert.deepEqual(json("getRouteSlotEntry('route1',0)"),{location:'b',stay:30});assert.deepEqual(json("getRouteSlotEntry('route2',0)"),{location:'a',stay:25})});
test('dropping onto original slot does not refresh or mutate',()=>{const {c,run,json,cost}=fixture();run("setRouteSlotEntry('route1',0,{location:'a',stay:25})");const node=element({listType:'route1',slot:'0',customerId:'a'});drag(c,node,node);assert.equal(json("getRouteSlotEntry('route1',0)").location,'a');assert.equal(cost.preview,0);assert.equal(c.draggedItemElement,null)});
test('Up/Down reordering skips empty slots and retains stay values',()=>{const {c,run,json}=fixture();run("setRouteSlotEntry('route1',0,{location:'a',stay:25});setRouteSlotEntry('route1',3,{location:'b',stay:30})");c.moveRouteSlotSequence('route1',0,'down');assert.deepEqual(json("getRouteWaypointIds('route1')"),['b','a']);assert.equal(json("getRouteSlotEntry('route1',3)").stay,25)});
test('remove then add uses existing unassigned and slot storage without persistence',()=>{const {c,run,json,cost}=fixture();run("setRouteSlotEntry('route1',0,{location:'a',stay:25})");c.removeFromSlot('route1',0);c.removeFromSlot('route1',0);assert.deepEqual(json('unassignedStops'),['a']);c.addUnassignedStopToNextRouteSlot('a');assert.deepEqual(json('unassignedStops'),[]);assert.equal(json("getRouteSlotEntry('route1',0)").location,'a');assert.equal(cost.writes,0);assert.equal(cost.netlify,0);assert.equal(cost.eta,0)});
test('native slot and unassigned drag bindings stay unique after repeated setup',()=>{const {c}=fixture();const slot=element(),item=element(),list=element();list.querySelectorAll=()=>[item];const container={querySelectorAll:()=>[slot]};c.attachDragListenersToSlots(container);c.attachDragListenersToSlots(container);c.attachDragListenersToUnassignedList(list);c.attachDragListenersToUnassignedList(list);assert.equal([...slot.events.values()].reduce((a,s)=>a+s.size,0),5);assert.equal([...item.events.values()].reduce((a,s)=>a+s.size,0),2);assert.equal([...list.events.values()].reduce((a,s)=>a+s.size,0),2)});
test('page uses existing finalization and preserves explicit Retrieve All session sync',()=>{const page=sources[1],dnd=sources[2];assert.doesNotMatch(dnd,/\bfetch\(|firebase\.|syncSessionToCloud\(|saveHistory\(/);assert.match(page,/function retrieveAllStopsFromRoutes\(\)[\s\S]*syncSessionToCloud\(\)/);const app=read('app.html');for(const name of ['manual-assignment-page','manual-assignment-dnd'])assert.equal(app.split('src="planning/'+name+'.js?').length-1,1);assert.match(read('planning/planning-page.js'),/confirmRouteConfirmBtn\.addEventListener\('click', handleConfirmRouteModalConfirm\)/)});
