import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../planning/manual-map-preview.js',import.meta.url),'utf8');
function fixture(){const counts={maps:0,bind:0,route:0,draw:0};const c=vm.createContext({Promise,console,setTimeout,clearTimeout,window:{_activeRoutes:[]},mapPage2:null,currentLatLng:null,route1DirectionsRenderer:null,route2DirectionsRenderer:null,optimizedRouteRenderer:null,manualPreviewRoutes:[],manualRouteCompletedKey:'',manualRouteInFlightKey:'',manualRoutePromise:null,manualRouteRun:0,manualRouteUpdateTimer:null,manualRoutePendingResolve:null,suggestedWaypointOrder:[],currentLocationOrigin:'origin',previewDirectionsService:{},dynamicRouteRenderersPage2:[],assignRouteColors:x=>x,syncManualWaypointsFromSlots(){},getCurrentConfiguredEndLocationId:()=>null,getLocationInput:x=>x,getRouteCacheKeyFromStops:s=>s.map(x=>x.id).join(','),getDynamicRouteStopInput:s=>s.id,getPackedRouteStopId:s=>s.id,clearTestDynamicRouteRenderers(){},renderManualDetourMarkers(){},updateConfirmRouteButtonState(){},bindManualDetourMap(){counts.bind++},MapHandler:{initMap(){counts.maps++;return {}},setDirections(){},route:async()=>{counts.route++;return {routes:[]}}},RouteSafety:{enabled:()=>false,settings:()=>({vehicle:'lorry'}),rulesVersion:'1',isCurrent:()=>true,showConflicts(){},invalidate(){},bindRoutes(){},validateRoutes:async()=>{}},RouteEngine:{buildRouteRequest:x=>({optimizedStops:x.stopIds,cacheKey:JSON.stringify(x),request:x})},getRouteDirectionsFromCache:()=>null,setRouteDirectionsCache:(r,result)=>{r.directionsResult=result},renderRouteLegColors:r=>{counts.draw++;c.drawn.push(r.id)},drawn:[],appLog(){}});vm.runInContext(source,c);c.renderManualRestrictionStatus=()=>{};return {c,counts}}
test('preview module load has no map or network side effects',()=>{const {c,counts}=fixture();assert.equal(typeof c.updateRouteLines,'function');assert.deepEqual(counts,{maps:0,bind:0,route:0,draw:0})});
test('manual map initializer honors existing needsInit guard and reuses instance',()=>{const {c,counts}=fixture();const el={querySelector:()=>true};c.initializeManualMapPreview(el,true);const map=c.mapPage2;c.initializeManualMapPreview(el,false);c.initializeManualMapPreview(el,false);assert.equal(c.mapPage2,map);assert.equal(counts.maps,1);assert.equal(counts.bind,1)});
test('preview draws route order without calculating routes or persisting',()=>{const {c,counts}=fixture();c.mapPage2={};c.drawManualPreviewRoutes([{id:'second',directionsResult:{}},{id:'first',directionsResult:{}}]);assert.deepEqual(c.drawn,['second','first']);assert.equal(counts.route,0);assert.doesNotMatch(source,/firebase\.|saveHistory\(|syncSessionToCloud\(|fetch\(|openDispatchPage\(/)});
test('matching completed input redraws without a new routing call',async()=>{const {c,counts}=fixture();c.manualRouteCompletedKey=c.getManualRouteInputKey([]);await c.updateRouteLines();assert.equal(c.manualRouteRun,0);assert.equal(counts.route,0)});
test('same in-flight key returns the existing promise',()=>{const {c}=fixture();c.manualRouteInFlightKey=c.getManualRouteInputKey([]);const pending=Promise.resolve([]);c.manualRoutePromise=pending;assert.equal(c.updateRouteLines(),pending);assert.equal(c.manualRouteRun,0)});
test('actual calculation preserves order and makes one request per uncached group',async()=>{const {c,counts}=fixture();c.mapPage2={};c.manualRouteRun=1;const routes=[{id:'r1',stops:[{id:'a'},{id:'b'}]},{id:'r2',stops:[{id:'c'}]}];await c.calculateManualRouteLines(1,routes,'key');assert.equal(counts.route,2);assert.deepEqual(c.drawn,['r1','r2']);assert.equal(c.manualRouteCompletedKey,'key')});
test('late Directions response cannot replace a newer preview run',async()=>{const {c,counts}=fixture();c.mapPage2={};c.manualRouteRun=1;let resolve;c.MapHandler.route=()=>new Promise(r=>resolve=r);const old=c.calculateManualRouteLines(1,[{id:'old',stops:[{id:'a'}]}],'old-key');c.manualRouteRun=2;c.manualPreviewRoutes=[{id:'new'}];resolve({routes:[]});await old;assert.equal(c.manualPreviewRoutes[0].id,'new');assert.equal(counts.draw,0);assert.equal(c.manualRouteCompletedKey,'')});
test('request identity changes with order and restriction settings',()=>{const {c}=fixture();const key=c.getManualRouteInputKey([{stops:[{id:'a'},{id:'b'}]}]);assert.notEqual(key,c.getManualRouteInputKey([{stops:[{id:'b'},{id:'a'}]}]));c.RouteSafety.settings=()=>({vehicle:'van'});assert.notEqual(key,c.getManualRouteInputKey([{stops:[{id:'a'},{id:'b'}]}]))});
