import test from 'node:test';import assert from 'node:assert/strict';import {suggestMapping,validateMapping} from '../orders/import-mapper.js';import {normalizeOrder,normalizeDate,clean} from '../orders/order-normalizer.js';import {validateOrder} from '../orders/import-validator.js';import {classifyDuplicate} from '../orders/duplicate-detector.js';import {makeProfile,matchProfile,applyProfile} from '../orders/import-profiles.js';import {parseDelimited,parsePaste,readFile} from '../orders/spreadsheet-reader.js';import {prepareImport} from '../orders/import-engine.js';import {readFile as fsReadFile} from 'node:fs/promises';import vm from 'node:vm';
const base={source:'FILE',orderId:'DO-1',customerName:'Acme',address:'12 Main Street',deliveryDate:'2026-10-01'};
test('header mapping exact aliases unknown reordered conflicts',()=>{assert.deepEqual(suggestMapping(['orderId','Debtor Name','Delivery Addr','mystery']).map(x=>x.field),['orderId','customerName','address','']);assert.deepEqual(suggestMapping(['Delivery Addr','Invoice No']).map(x=>x.field),['address','orderId']);assert.throws(()=>validateMapping(['orderId','orderId']),/more than once/);});
test('phone blanks dates and numeric normalization',()=>{const {order,issues}=normalizeOrder({phone:' 012-345 6789 ',notes:'N/A',deliveryDate:'27/09/2026',quantity:'1,200',weight:'2.5'});assert.equal(order.phone,'0123456789');assert.equal(order.notes,null);assert.equal(order.deliveryDate,'2026-09-27');assert.equal(order.quantity,1200);assert.equal(order.weight,2.5);assert.deepEqual(issues,[]);assert.equal(clean('-'),null);assert.equal(normalizeDate(45292),'2024-01-01');});
test('ready missing address malformed values corrected to ready',()=>{assert.equal(validateOrder(base).status,'READY');assert.equal(validateOrder({...base,address:''}).status,'NEEDS_REVIEW');const bad=normalizeOrder({...base,deliveryDate:'bad',quantity:'no'});assert.equal(validateOrder(bad.order,bad.issues).status,'NEEDS_REVIEW');const fixed=normalizeOrder({...base,deliveryDate:'2026-10-01',quantity:'2'});assert.equal(validateOrder(fixed.order,fixed.issues).status,'READY');});
test('exact possible and distinct duplicates',()=>{assert.equal(classifyDuplicate(base,[base]).kind,'EXACT');assert.equal(classifyDuplicate({...base,orderId:'DO-2'},[base]).kind,'POSSIBLE');assert.equal(classifyDuplicate({...base,orderId:'DO-2',address:'Another Road'},[base]),null);});
test('profiles survive reordered columns',()=>{const p=makeProfile('ERP',['Invoice No','Delivery Addr'],['orderId','address']);assert.equal(matchProfile([p],['Delivery Addr','Invoice No']).id,p.id);assert.deepEqual(applyProfile(p,['Delivery Addr','Invoice No']),['address','orderId']);assert.equal(matchProfile([p],['Customer','Delivery Addr']),null);});
test('CSV paste and XLSX use same table shape',async()=>{const csv=parseDelimited('Invoice No,Delivery Addr,Customer\nDO-1,12 Main Street,Acme',',');assert.deepEqual(csv,parsePaste('Invoice No\tDelivery Addr\tCustomer\nDO-1\t12 Main Street\tAcme'));vm.runInThisContext(await fsReadFile(new URL('../vendor/xlsx.full.min.js',import.meta.url),'utf8'));const book=globalThis.XLSX.utils.book_new();globalThis.XLSX.utils.book_append_sheet(book,globalThis.XLSX.utils.aoa_to_sheet([csv.headers,...csv.rows]),'Orders');const bytes=globalThis.XLSX.write(book,{bookType:'xlsx',type:'array'});assert.deepEqual(await readFile({name:'orders.xlsx',arrayBuffer:async()=>bytes}),csv);});
test('parser errors and partial import',()=>{assert.throws(()=>parseDelimited('A,B',','),/header/);assert.throws(()=>parseDelimited('Order ID,Order-ID\n1,2',','),/Duplicate/);assert.throws(()=>parseDelimited('Order ID,Address\n1,12 Road,extra',','),/more values/);const rows=prepareImport(parseDelimited('Order ID,Address\nA-1,12 Main Street\nA-2,\nA-1,12 Main Street',','),['orderId','address'],[],{source:'FILE'});assert.deepEqual(rows.map(r=>r.status),['READY','NEEDS_REVIEW','DUPLICATE']);});
