import {DriverRouteStore} from './route-store.js';
import {progress,snapshotRouteStops} from './route-model.js';
import {navigationUrl,callUrl} from './navigation.js';
import {loadContactRequired} from '../orders/master-data.js';
const $=id=>document.getElementById(id);
const state={user:null,store:null,routes:[],route:null,execution:null,busy:false,contactRequired:false,photoUrl:null,selectedStopId:null};
function notice(message='',error=false){const node=$('driverNotice');node.textContent=message;node.classList.toggle('is-error',error);node.hidden=!message;}
function label(value,fallback='—'){return String(value??'').trim()||fallback;}
function stopRows(){return state.execution?.stops||snapshotRouteStops(state.route);}
function displayStop(stop){const node=$('driverStopDetail');if(!stop){node.hidden=true;return;}node.replaceChildren();const title=document.createElement('strong');title.textContent=`${stop.sequence}. ${stop.stopName}`;const body=document.createElement('p');body.textContent=[stop.deliveryAddress,stop.contactName,stop.contactPhone,...(stop.orderIds||[]),stop.failureReason,stop.failureNotes].filter(Boolean).join(' · ');node.append(title,body);node.hidden=false;}
function routeChoices(){const list=$('driverRouteList');list.replaceChildren();if(!state.routes.length){const empty=document.createElement('p');empty.textContent='No route assigned. Your dispatcher will add one when it is ready.';list.append(empty);return;}for(const route of state.routes){const button=document.createElement('button');button.type='button';button.className='driver-route-choice';button.dataset.routeId=route.id;button.setAttribute('aria-current',String(state.route?.id===route.id));const title=document.createElement('strong');title.textContent=route.routeName||`Route ${route.id}`;const meta=document.createElement('small');meta.textContent=[route.date||route.planningDate,route.vehicleDriver].filter(Boolean).join(' · ')||'Saved route';button.append(title,meta);list.append(button);}}
function render(){routeChoices();const route=state.route,execution=state.execution;$('driverRouteView').hidden=!route;if(!route)return;const stops=stopRows(),p=progress(stops);$('driverRouteName').textContent=label(route.routeName,`Route ${route.id}`);$('driverRouteDate').textContent=label(route.date||route.planningDate,'Saved route');$('driverRouteMeta').textContent=[route.vehicleDriver?`Driver / vehicle: ${route.vehicleDriver}`:'',`${p.total} stops`,route.orderLinkStatus==='UNAVAILABLE'?'Order Hub links unavailable when saved':route.orderLinkStatus==='AMBIGUOUS'?'Some orders need route review':null].filter(Boolean).join(' · ');$('driverRouteStatus').textContent=execution?.status||'ASSIGNED';$('driverProgress').innerHTML='';const strong=document.createElement('strong');strong.textContent=`${p.processed} / ${p.total} processed`;const extra=document.createElement('span');extra.textContent=` · ${p.delivered} delivered · ${p.failed} failed · ${p.remaining} remaining`;$('driverProgress').append(strong,extra);$('driverStartArea').hidden=!!execution;$('driverStartBtn').disabled=state.busy;const active=execution?.status==='IN_PROGRESS';$('driverNextStop').hidden=!active||!p.next;$('driverFinishArea').hidden=!active||!!p.next;
 if(active&&p.next){const stop=p.next;$('driverStopSequence').textContent=`Stop ${stop.sequence} of ${p.total} · ${stop.executionStatus==='ARRIVED'?'Arrived':'Next stop'}`;$('driverStopName').textContent=label(stop.stopName);$('driverStopCustomer').textContent=stop.customerName&&stop.customerName!==stop.stopName?stop.customerName:'';$('driverStopAddress').textContent=label(stop.deliveryAddress,'Delivery address missing — contact operations');$('driverStopContact').textContent=stop.contactName?[stop.contactName,stop.contactPhone].filter(Boolean).join(' · '):state.contactRequired?'Contact missing in saved route':'No contact listed';$('driverStopNotes').textContent=stop.notes||'';const orders=$('driverStopOrders');orders.replaceChildren();for(const id of stop.orderNumbers?.length?stop.orderNumbers:stop.orderIds||[]){const chip=document.createElement('span');chip.textContent=id;orders.append(chip);}const nav=navigationUrl(stop),call=callUrl(stop);$('driverNavigate').hidden=!nav;if(nav)$('driverNavigate').href=nav;else $('driverNavigate').removeAttribute('href');$('driverCall').hidden=!call;if(call)$('driverCall').href=call;else $('driverCall').removeAttribute('href');$('driverArriveBtn').hidden=stop.executionStatus!=='PENDING';$('driverDeliverBtn').hidden=stop.executionStatus!=='ARRIVED';$('driverFailBtn').hidden=false;for(const id of ['driverArriveBtn','driverDeliverBtn','driverFailBtn'])$(id).disabled=state.busy;}
 if(active&&!p.next){$('driverFinishSummary').textContent=`${p.delivered} delivered, ${p.failed} failed. The failed stops will remain failed.`;$('driverFinishBtn').disabled=state.busy;}
 const list=$('driverStopList');list.replaceChildren();for(const stop of stops){const button=document.createElement('button');button.type='button';button.className=`driver-stop-item is-${String(stop.executionStatus||'PENDING').toLowerCase()}${p.next?.id===stop.id?' is-current':''}`;button.dataset.stopId=stop.id;const num=document.createElement('strong');num.textContent=String(stop.sequence).padStart(2,'0');const copy=document.createElement('span');const title=document.createElement('strong');title.textContent=stop.stopName;const sub=document.createElement('small');sub.textContent=`${stop.executionStatus||'PENDING'} · ${stop.deliveryAddress||'Address unavailable'}`;copy.append(title,sub);button.append(num,copy);list.append(button);}displayStop(stops.find(stop=>stop.id===state.selectedStopId)||null);}
async function loadRoutes(preferredId){if(!state.user)return;notice('Loading assigned routes…');state.routes=await state.store.listAssignedRoutes();const id=preferredId||new URLSearchParams(location.search).get('routeId')||state.route?.id||state.routes[0]?.id;state.route=state.routes.find(route=>String(route.id)===String(id))||(!preferredId?state.routes[0]:null)||null;state.store.mode=state.route?.__storageMode||state.store.baseMode;state.store.dispatchOwnerUid=state.route?.dispatchOwnerUid||null;state.execution=state.route?await state.store.loadExecution(state.route.id):null;if(state.route?.dispatchOwnerUid)state.store.retryPendingOrderSync(state.route.id).catch(console.warn);state.selectedStopId=null;render();notice(state.route?'':'No route assigned.');if(state.route&&state.execution?.status==='IN_PROGRESS')await resumeTracking();else if(state.route&&state.execution?.status==='COMPLETED'&&await waitTrackingReady()){try{window.DriverTrackingPage.setRouteContext(state.route);if(window.DriverTrackingPage.getStatus()!=='stopped')await window.DriverTrackingPage.stopTracking();}catch(error){notice(`Route complete, but tracking status could not sync: ${error.message}`,true);}}else if(!state.route&&await waitTrackingReady()&&!['ready','stopped'].includes(window.DriverTrackingPage.getStatus())){try{await window.DriverTrackingPage.stopTracking();}catch(error){notice(`Location status could not sync: ${error.message}`,true);}}}
async function waitTrackingReady(){if(window.DriverTrackingPage?.isReady?.())return true;return new Promise(resolve=>{const timer=setTimeout(()=>resolve(false),8000);window.addEventListener('goroutex:tracking-ready',()=>{clearTimeout(timer);resolve(true);},{once:true});});}
async function resumeTracking(){if(!await waitTrackingReady()){notice('Route is active. Location module is unavailable; reload to retry.',true);return;}try{window.DriverTrackingPage.setRouteContext(state.route);if(window.DriverTrackingPage.getStatus()!=='active'){const started=await window.DriverTrackingPage.startTracking();if(!started)notice('Route is active. Location unavailable; check browser permission and try refreshing.',true);}}catch(error){notice(`Route is active. Location unavailable: ${error.message}`,true);}}
async function perform(work){if(state.busy)return;state.busy=true;render();notice('Saving…');try{await work();render();}catch(error){notice(`${error.message||'Save failed.'} Retry the action.`,true);}finally{state.busy=false;render();}}
async function compressPhoto(file){if(!file)return null;if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Choose a JPEG, PNG or WebP photo.');if(file.size>15_000_000)throw Error('Photo exceeds 15 MB. Choose a smaller image.');const bitmap=await createImageBitmap(file);try{let scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));for(let attempt=0;attempt<4;attempt++){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',Math.max(.52,.8-attempt*.08));if(data.length<=550000)return data;scale*=.75;}throw Error('Photo is still too large after resizing. Choose a smaller image.');}finally{bitmap.close?.();}}
function hideForms(){$('driverPodForm').hidden=true;$('driverFailureForm').hidden=true;}
function clearPhoto(){if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);state.photoUrl=null;$('driverPhoto').value='';$('driverPhotoPreview').hidden=true;$('driverPhotoClear').hidden=true;}
function bind(){
 $('driverRefreshBtn').onclick=()=>perform(async()=>{await loadRoutes();notice('Routes refreshed.');});$('driverRouteList').onclick=event=>{const button=event.target.closest('[data-route-id]');if(button&&!state.busy)perform(async()=>{if(state.execution?.status==='IN_PROGRESS'&&state.route?.id!==button.dataset.routeId)throw Error('Complete the active route before switching.');await loadRoutes(button.dataset.routeId);notice('');});};$('driverStopList').onclick=event=>{const button=event.target.closest('[data-stop-id]');if(button){state.selectedStopId=button.dataset.stopId;displayStop(stopRows().find(stop=>stop.id===state.selectedStopId));}};
 $('driverStartBtn').onclick=()=>perform(async()=>{state.execution=await state.store.start(state.route);notice('Route started. Starting location sharing…');await resumeTracking();});
 $('driverArriveBtn').onclick=()=>perform(async()=>{const stop=progress(state.execution.stops).next;state.execution=await state.store.arrive(state.route.id,stop.id,window.DriverTrackingPage?.getLatestPosition?.());notice(`${stop.stopName}: arrival saved.`);});
 $('driverDeliverBtn').onclick=()=>{hideForms();const stop=progress(state.execution.stops).next;$('driverRecipient').value=stop.contactName||'';$('driverPodForm').hidden=false;$('driverPodForm').scrollIntoView({behavior:'smooth',block:'center'});};$('driverPodCancel').onclick=()=>{$('driverPodForm').hidden=true;clearPhoto();$('driverPodForm').reset();};$('driverPhoto').onchange=()=>{if(state.photoUrl)URL.revokeObjectURL(state.photoUrl);const file=$('driverPhoto').files?.[0];state.photoUrl=file?URL.createObjectURL(file):null;$('driverPhotoPreview').hidden=!state.photoUrl;$('driverPhotoClear').hidden=!state.photoUrl;if(state.photoUrl)$('driverPhotoPreview').src=state.photoUrl;};$('driverPhotoClear').onclick=clearPhoto;
 $('driverPodForm').onsubmit=event=>{event.preventDefault();perform(async()=>{const stop=progress(state.execution.stops).next,photo=await compressPhoto($('driverPhoto').files?.[0]);state.execution=await state.store.deliver(state.route.id,stop.id,{recipientName:$('driverRecipient').value,notes:$('driverPodNotes').value,photoDataUrl:photo,position:window.DriverTrackingPage?.getLatestPosition?.()});hideForms();clearPhoto();$('driverPodForm').reset();notice(`${stop.stopName} delivered. Next stop is ready.`);});};
 $('driverFailBtn').onclick=()=>{hideForms();$('driverFailureForm').hidden=false;$('driverFailureForm').scrollIntoView({behavior:'smooth',block:'center'});};$('driverFailureCancel').onclick=()=>{$('driverFailureForm').hidden=true;$('driverFailureForm').reset();};$('driverFailureForm').onsubmit=event=>{event.preventDefault();perform(async()=>{const stop=progress(state.execution.stops).next;state.execution=await state.store.fail(state.route.id,stop.id,$('driverFailureReason').value,$('driverFailureNotes').value,window.DriverTrackingPage?.getLatestPosition?.());hideForms();$('driverFailureForm').reset();notice(`${stop.stopName} marked failed. Continue to the next stop.`);});};
 $('driverFinishBtn').onclick=()=>perform(async()=>{state.execution=await state.store.finish(state.route.id);const stopped=await window.DriverTrackingPage?.stopTracking?.();notice(stopped?'Route completed. Location sharing stopped.':'Route completed. Location stopped on this device; remote status will retry when online.',!stopped);});
}
bind();
if(!window.FirebaseApp?.auth?.onAuthStateChange)notice('Sign-in service is unavailable. Reload this page.',true);else window.FirebaseApp.auth.onAuthStateChange(async user=>{if(!user){notice('Sign in to view your assigned routes.',true);return;}state.user=user;try{const profileResult=await window.FirebaseApp.auth.getProfile?.();const profile=profileResult?.success?profileResult.profile||{}:{};if(!window.FirebaseApp.auth.isDriverAccount?.(user)||profile.role!=='driver'||profile.active===false){notice('Driver account required. Use Driver Login.',true);return;}state.store=await DriverRouteStore.create(user,profile);try{state.contactRequired=await loadContactRequired(user.uid);}catch{state.contactRequired=false;}await loadRoutes();}catch(error){notice(`Could not load assigned routes: ${error.message}`,true);}});
