import {progress,snapshotRouteStops} from './route-model.js';
const now=()=>new Date().toISOString();
const find=(execution,stopId)=>{const stop=execution.stops.find(item=>item.id===stopId);if(!stop)throw Error('This stop is no longer on the route. Refresh the route.');return stop;};
const assertActive=execution=>{if(!execution||execution.status!=='IN_PROGRESS')throw Error('Start this route before recording delivery activity.');};
export function startExecution(route,driverUid){if(!route?.id||route.assignedDriverUid!==driverUid)throw Error('This route is not assigned to your account.');const stops=snapshotRouteStops(route);if(!stops.length)throw Error('The saved route has no delivery stops. Review it in route planning.');return {routeId:String(route.id),ownerUid:driverUid,assignedDriverUid:driverUid,driverLabel:route.driverName||route.vehicleDriver||'',vehicleLabel:route.vehicleDriver||'',routeName:route.routeName||`Route ${route.id}`,routeDate:route.date||route.planningDate||null,status:'IN_PROGRESS',actualStartAt:now(),actualEndAt:null,stops,updatedAt:now()};}
export function arrive(execution,stopId,position){assertActive(execution);const stop=find(execution,stopId);if(stop.executionStatus==='ARRIVED')return execution;if(stop.executionStatus!=='PENDING')throw Error('This stop is already processed.');const at=now();return {...execution,stops:execution.stops.map(item=>item.id===stopId?{...item,executionStatus:'ARRIVED',actualArrivalAt:at,actualArrivalLat:position?.lat??null,actualArrivalLng:position?.lng??null,arrivalAccuracy:position?.accuracy??null}:item),updatedAt:at};}
export function deliver(execution,stopId,pod){assertActive(execution);const stop=find(execution,stopId);if(stop.executionStatus==='DELIVERED')return execution;if(stop.executionStatus!=='ARRIVED')throw Error('Mark this stop Arrived before completing delivery.');const at=now();return {...execution,stops:execution.stops.map(item=>item.id===stopId?{...item,executionStatus:'DELIVERED',actualCompletedAt:at,podId:pod.id}:item),updatedAt:at};}
export function fail(execution,stopId,reason,notes='',position){assertActive(execution);const stop=find(execution,stopId);if(stop.executionStatus==='FAILED')return execution;if(!['PENDING','ARRIVED'].includes(stop.executionStatus))throw Error('This stop is already delivered.');if(!String(reason||'').trim())throw Error('Select a failure reason.');if(reason==='Other'&&!String(notes||'').trim())throw Error('Add a note for Other.');const at=now();return {...execution,stops:execution.stops.map(item=>item.id===stopId?{...item,executionStatus:'FAILED',failedAt:at,failureReason:reason,failureNotes:String(notes||'').trim(),failedLat:position?.lat??null,failedLng:position?.lng??null}:item),updatedAt:at};}
export function finish(execution){assertActive(execution);if(progress(execution.stops).remaining)throw Error('Process every stop before completing this route.');const at=now();return {...execution,status:'COMPLETED',actualEndAt:at,updatedAt:at};}
