const panel=document.getElementById('driverOperationsPanel');
const list=document.getElementById('driverOperationsList');
const status=document.getElementById('driverOperationsStatus');
if(panel&&list&&status&&window.FirebaseApp?.auth?.onAuthStateChange){
 let live=[],executions=[],unsubscribeLive=null,unsubscribeExecutions=null,activeUid=null,renderTimer=null;
 const date=value=>{if(!value)return null;const parsed=typeof value.toDate==='function'?value.toDate():new Date(value);return Number.isNaN(parsed.getTime())?null:parsed;};
 const element=(tag,text,className)=>{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;};
 const stopSubscriptions=()=>{unsubscribeLive?.();unsubscribeExecutions?.();unsubscribeLive=null;unsubscribeExecutions=null;if(renderTimer){clearInterval(renderTimer);renderTimer=null;}};
 function render(){list.replaceChildren();const sorted=[...executions].sort((a,b)=>(date(b.updatedAt)?.getTime()||0)-(date(a.updatedAt)?.getTime()||0)).slice(0,6);if(!sorted.length){list.append(element('p','No route execution yet. Start a saved route from Driver Page.','driver-operations-empty'));status.textContent='Waiting for route activity';return;}status.textContent=`${executions.filter(row=>row.status==='IN_PROGRESS').length} route${executions.filter(row=>row.status==='IN_PROGRESS').length===1?'':'s'} in progress`;
  for(const row of sorted){const gps=live.find(item=>item.routeId===row.routeId&&item.driverId===row.assignedDriverUid);const stops=Array.isArray(row.stops)?row.stops:[];const delivered=stops.filter(stop=>stop.executionStatus==='DELIVERED').length,failed=stops.filter(stop=>stop.executionStatus==='FAILED').length;const current=stops.find(stop=>!['DELIVERED','FAILED'].includes(stop.executionStatus));const card=element('article','','driver-operations-item');const top=element('div','','driver-operations-top');top.append(element('strong',row.routeName||`Route ${row.routeId}`),element('span',row.status==='IN_PROGRESS'?'In progress':'Completed',`driver-operations-chip ${row.status==='IN_PROGRESS'?'is-active':''}`));card.append(top,element('p',`${delivered+failed} / ${stops.length} processed · ${delivered} delivered · ${failed} failed`),element('p',current?`Current stop: ${current.stopName}`:'All stops processed'));
   const updated=date(gps?.lastUpdatedAt||gps?.lastUploadedClientAt),age=updated?Date.now()-updated.getTime():Infinity;const gpsState=!gps?'No GPS update':gps.status==='stopped'?'Tracking stopped':age>90000?'GPS stale':'GPS current';const time=updated?updated.toLocaleString():'No update yet';card.append(element('p',`${gpsState} · Last update: ${time}`));if(gps&&Number.isFinite(gps.lat)&&Number.isFinite(gps.lng)){const link=element('a',`${gps.lat.toFixed(5)}, ${gps.lng.toFixed(5)} · Open map`);link.href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${gps.lat},${gps.lng}`)}`;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}list.append(card);}
 }
 window.FirebaseApp.auth.onAuthStateChange(async user=>{if(!user){activeUid=null;stopSubscriptions();list.replaceChildren();status.textContent='Sign in to see route activity';return;}if(activeUid===user.uid)return;stopSubscriptions();activeUid=user.uid;try{const profileResult=await window.FirebaseApp.auth.getProfile?.();if(activeUid!==user.uid)return;const profile=profileResult?.success?profileResult.profile||{}:{};const resolved=await window.RoutePlannerStorage.getResolvedStorage(profile,{allowMigration:false});if(activeUid!==user.uid)return;if(resolved.storageMode==='indexeddb'){status.textContent='Local storage mode';list.replaceChildren(element('p','Route execution is stored on this device. Open Driver Page here to view it.','driver-operations-empty'));return;}const root=firebase.firestore().collection('users').doc(user.uid);unsubscribeExecutions=root.collection('driverExecutions').limit(30).onSnapshot(snapshot=>{executions=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));render();},error=>{status.textContent=`Route activity unavailable: ${error.message}`;});unsubscribeLive=window.FirebaseApp.tracking.subscribeLiveDrivers(rows=>{live=rows;render();},{limitCount:30});renderTimer=setInterval(render,30000);}catch(error){status.textContent=`Route activity unavailable: ${error.message}`;}});
}
