import {startExecution,arrive,deliver,fail,finish} from './execution.js';
import {readLocal,writeLocal,mutateLocal} from './local-execution-db.js';
const name=(routeId,stopId)=>`${encodeURIComponent(routeId)}_${encodeURIComponent(stopId)}`;
export class DriverRouteStore{
 constructor(user,profile,mode){this.uid=user.uid;this.profile=profile;this.mode=mode;this.baseMode=mode;this.dispatchOwnerUid=null;this.root=firebase.firestore().collection('users').doc(user.uid);}
 static async create(user,profile){if(user.uid.startsWith('drv_'))return new DriverRouteStore(user,profile,'cloud');const resolved=await window.RoutePlannerStorage.getResolvedStorage(profile,{allowMigration:false});return new DriverRouteStore(user,profile,resolved.storageMode);}
 executionRef(id){return this.root.collection('driverExecutions').doc(String(id));}
 async listAssignedRoutes(){let routes=[];if(this.baseMode==='indexeddb'){let offset=0,hasMore=true;while(hasMore){const result=await window.RoutePlannerStorage.loadHistory({profile:this.profile,limit:50,offset});if(!result.success)throw Error(result.error||'Could not load saved routes.');routes.push(...(result.routes||[]).map(route=>({...route,__storageMode:'indexeddb'})));offset+=result.routes?.length||0;hasMore=Boolean(result.hasMore&&result.routes?.length);}}try{const snapshot=await this.root.collection('history').where('assignedDriverUid','==',this.uid).get();routes.push(...snapshot.docs.map(doc=>({id:doc.id,...doc.data(),__storageMode:'cloud'})));}catch(error){if(this.baseMode!=='indexeddb')throw error;console.warn('Cloud assignments unavailable; showing local routes:',error);}const unique=[...new Map(routes.map(route=>[String(route.id),route])).values()];return unique.filter(route=>route.assignedDriverUid===this.uid&&Array.isArray(route.plannedRoutes)&&route.plannedRoutes.length).sort((a,b)=>String(b.date||b.planningDate||'').localeCompare(String(a.date||a.planningDate||''))||String(b.timestamp||'').localeCompare(String(a.timestamp||'')));}
 async loadRoute(id){if(this.mode==='indexeddb'){const routes=await this.listAssignedRoutes();return routes.find(route=>String(route.id)===String(id))||null;}const doc=await this.root.collection('history').doc(String(id)).get();const route=doc.exists?{id:doc.id,...doc.data()}:null;return route?.assignedDriverUid===this.uid?route:null;}
 async loadExecution(id){if(this.mode==='indexeddb')return readLocal(`${this.uid}:execution:${id}`);const doc=await this.executionRef(id).get();return doc.exists?doc.data():null;}
 async mutate(id,fn,{pod=null,orderIds=[],outcome=null}={}){if(this.mode==='indexeddb'){if(pod)await writeLocal(`${this.uid}:pod:${pod.id}`,pod);return mutateLocal(`${this.uid}:execution:${id}`,fn);}const ref=this.executionRef(id);return firebase.firestore().runTransaction(async tx=>{const doc=await tx.get(ref),before=doc.exists?doc.data():null,next=fn(before);if(next===before)return before;const orderDocs=this.dispatchOwnerUid?[]:await Promise.all(orderIds.map(orderId=>tx.get(this.root.collection('orders').doc(orderId))));tx.set(ref,next);if(pod)tx.set(this.root.collection('driverPods').doc(pod.id),pod);orderDocs.forEach((orderDoc,index)=>{if(orderDoc.exists)tx.set(this.root.collection('orders').doc(orderIds[index]),{executionStatus:outcome,driverRouteId:id,executionUpdatedAt:new Date().toISOString()},{merge:true});});return next;});}
 async syncDispatchedOrders(id,stopId,outcome){if(!this.dispatchOwnerUid)return;const pendingKey=`grxOrderSync:${this.uid}:${id}:${stopId}`;try{localStorage.setItem(pendingKey,outcome);}catch{}const token=await firebase.auth().currentUser.getIdToken();const response=await fetch('/.netlify/functions/dispatch',{method:'POST',headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'sync-order',dispatchId:id,stopId,outcome})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.error||'Order Hub status sync failed.');try{localStorage.removeItem(pendingKey);}catch{}}
 async retryPendingOrderSync(id){if(!this.dispatchOwnerUid)return;const prefix=`grxOrderSync:${this.uid}:${id}:`;for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key?.startsWith(prefix))continue;const stopId=key.slice(prefix.length),outcome=localStorage.getItem(key);try{await this.syncDispatchedOrders(id,stopId,outcome);index--;}catch(error){console.warn('Order Hub status sync pending:',error);}}}
 async start(route){return this.mutate(route.id,current=>current||startExecution(route,this.uid));}
 async arrive(id,stopId,position){return this.mutate(id,current=>arrive(current,stopId,position));}
 async deliver(id,stopId,{recipientName='',notes='',photoDataUrl=null,position=null}={}){const existing=await this.loadExecution(id),stop=existing?.stops.find(item=>item.id===stopId);if(stop?.executionStatus==='DELIVERED'){await this.syncDispatchedOrders(id,stopId,'DELIVERED').catch(console.warn);return existing;}if(!stop||stop.executionStatus!=='ARRIVED')throw Error('Mark this stop Arrived before completing delivery.');const podId=name(id,stopId),photoId=photoDataUrl?`photo_${podId}`:null;if(photoDataUrl)await this.savePhoto(photoId,photoDataUrl,id);const pod={id:podId,routeId:id,stopId,ownerUid:this.uid,recipientName:String(recipientName||'').trim(),notes:String(notes||'').trim(),photoId,completedAt:new Date().toISOString(),lat:position?.lat??null,lng:position?.lng??null};const next=await this.mutate(id,current=>deliver(current,stopId,pod),{pod,orderIds:stop.orderIds||[],outcome:'DELIVERED'});await this.syncDispatchedOrders(id,stopId,'DELIVERED').catch(error=>console.warn('Delivery saved; Order Hub sync pending:',error));return next;}
 async fail(id,stopId,reason,notes,position){const existing=await this.loadExecution(id),stop=existing?.stops.find(item=>item.id===stopId);const next=await this.mutate(id,current=>fail(current,stopId,reason,notes,position),{orderIds:stop?.orderIds||[],outcome:'FAILED'});await this.syncDispatchedOrders(id,stopId,'FAILED').catch(error=>console.warn('Failure saved; Order Hub sync pending:',error));return next;}
 async finish(id){return this.mutate(id,current=>finish(current));}
 async savePhoto(id,dataUrl,routeId){if(!/^data:image\/(jpeg|png|webp);base64,/.test(dataUrl)||dataUrl.length>550000)throw Error('Photo is too large or unsupported. Choose a smaller JPEG, PNG or WebP image.');const record={id,ownerUid:this.uid,routeId,dataUrl,createdAt:new Date().toISOString()};if(this.mode==='indexeddb')await writeLocal(`${this.uid}:photo:${id}`,record);else await this.root.collection('driverPodPhotos').doc(id).set(record);return id;}
 async loadPhoto(id){if(!id)return null;if(this.mode==='indexeddb')return readLocal(`${this.uid}:photo:${id}`);const doc=await this.root.collection('driverPodPhotos').doc(id).get();return doc.exists?doc.data():null;}
}
